@startuml architecture
left to right direction

class Item
class DisplayableItem
class Road
class Car
class Conditions
class NoCar
class DisplayblePath

skinparam style strictuml
skinparam linetype ortho


' Positioning
Item -[hidden]-> Road
Road -[hidden]-> Car
Conditions -[hidden]-> Car : ""
Car -[hidden]-> NoCar

' Relations
Road --> Conditions
Road --> Item
Car --> Conditions
NoCar --|> Car

DisplayableItem --> Item
DisplayblePath --> Road

' Explicit layout
Item -[hidden]left-> Road
Road -[hidden]left-> Car
Conditions -[hidden]down-> Car
Car -[hidden]down-> NoCar

@enduml